version: '2.3'

services:
  files:
    build:
      context: .
    volumes:
      - "./:/service"
    environment:
      - MASTER_KEY=${MASTER_KEY:-KTVciAUQFpFh2WdJ/oiHJlxl6FvzRZp8kYzAAv3l2OA=}
      - DOMAIN="marseyverse.xyz"
      - FORCE_HTTPS="1"
      - DEFAULT_THEME="midnight"
      - DEFAULT_COLOR="7f8fa6"
    ports:
      - "80:80"